Update Black to non-beta to prevent build failures
Updated to fix this:

ImportError: /home/runner/.virtualenvs/.venv/lib/python3.9/site-packages/typed_ast/_ast3.cpython-39-x86_64-linux-gnu.so: undefined symbol: _PyUnicode_DecodeUnicodeEscape